general {
    disable_loading_bar = false
    hide_cursor = true
    ignore_empty_input = true
    text_trim = true
}

background {
    monitor = 
    path = ~/.config/hypr/wallpapers/wallpaper-3.png
    
    blur_passes     = 2
    blur_size       = 4

    brightness      = 0.7172
}

# TIME
label {
    monitor = eDP-1
    text = cmd[update:1000] echo "$(date +"%H")"
    # color = $foreground
    color = rgba(D8DEE9FF)
    font_size = 168
    font_family = Heavitas
    position = 0, -300
    halign = center
    valign = top
}
label {
    monitor = eDP-1
    text = cmd[update:1000] echo "$(date +"%M")"
    # color = $foreground
    color = rgba(D8DEE9FF)
    font_size = 168
    font_family = Heavitas
    position = 0, -500
    halign = center
    valign = top
}

# DATE
label {
    monitor = eDP-1
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    color = rgba(D8DEE9FF)
    font_size = 16
    font_family = FiraCode Nerd Font
    position = 0, -100
    halign = center
    valign = center
}


# LOCATION & WEATHER 
label {
    monitor = eDP-1
    text = cmd[update:1000] echo "$(bash ~/.config/hypr/bin/location-weather.sh)"
    color = rgba(255, 255, 255, 1)
    fade_on_empty = false
    font_size = 16
    font_family = FiraCode Nerd Font
    position = 0, 500
    halign = center
    valign = center
}

input-field {
    monitor = eDP-1
    size = 200, 50
    outline_thickness = 0
    dots_size = 0.33
    dots_spacing = 0.22 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = false
    outer_color = 
    inner_color = rgb(d8dee9ff)
    font_color = rgb(2e3440ff)
    fade_on_empty = false
    placeholder_text = <i>   $USER</i> # Text rendered in the input box when it's empty.
    hide_input = false

    check_color = rgb(d08770)
    fail_color = rgb(BF616A)

    position = 0, -470
    halign = center
    valign = center
}
